#!/usr/bin/env bash
set -euo pipefail

# Roka -- Zero-config bootstrap
# Generates all secrets and writes infra/.env with no user input.
# Set ROKA_DOMAIN to a domain or IP to configure for production.
# Usage:  cd infra && ./setup.sh && docker compose up -d

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"

if [ -f "$ENV_FILE" ]; then
  echo "infra/.env already exists. Remove it first to regenerate."
  exit 1
fi

echo "Generating secrets..."

POSTGRES_PASSWORD=$(openssl rand -hex 32)
JWT_SECRET=$(openssl rand -hex 32)
DASHBOARD_PASSWORD=$(openssl rand -hex 16)

# Derive Supabase JWT tokens from JWT_SECRET using Python (required for backend anyway)
read -r ANON_KEY SERVICE_ROLE_KEY <<< "$(python3 -c "
import hmac, hashlib, base64, json, sys

def b64url(data):
    return base64.urlsafe_b64encode(data).rstrip(b'=').decode()

secret = '${JWT_SECRET}'
compact = {'separators': (',', ':')}

header = b64url(json.dumps({'alg':'HS256','typ':'JWT'}, **compact).encode())

for role in ['anon', 'service_role']:
    payload = b64url(json.dumps({'iss':'supabase','role':role,'iat':1700000000,'exp':2000000000}, **compact).encode())
    msg = f'{header}.{payload}'.encode()
    sig = b64url(hmac.new(secret.encode(), msg, hashlib.sha256).digest())
    sys.stdout.write(f'{header}.{payload}.{sig} ')
")"

# Determine public URLs based on ROKA_DOMAIN env var
if [ -n "${ROKA_DOMAIN:-}" ]; then
  # IP check: all digits and dots
  if echo "$ROKA_DOMAIN" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$'; then
    PUBLIC_URL="http://${ROKA_DOMAIN}"
  else
    PUBLIC_URL="https://${ROKA_DOMAIN}"
  fi
  SITE_URL="$PUBLIC_URL"
  SUPABASE_EXT_URL="$PUBLIC_URL"
  ALLOW_LIST="${PUBLIC_URL}/**"
else
  PUBLIC_URL="http://localhost:8080"
  SITE_URL="http://localhost:3000"
  SUPABASE_EXT_URL="http://localhost:8080"
  ALLOW_LIST="http://localhost:3000/**"
fi

echo "Writing ${ENV_FILE} ..."

cat > "$ENV_FILE" <<ENVEOF
############
# Secrets (auto-generated by setup.sh)
############

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
JWT_SECRET=${JWT_SECRET}
ANON_KEY=${ANON_KEY}
SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
DASHBOARD_USERNAME=supabase
DASHBOARD_PASSWORD=${DASHBOARD_PASSWORD}

############
# Database
############

POSTGRES_HOST=db
POSTGRES_DB=postgres
POSTGRES_PORT=5432

############
# Supabase URLs (internal Docker network)
############

SUPABASE_URL=http://kong:8000
SUPABASE_PUBLIC_URL=${SUPABASE_EXT_URL}
API_EXTERNAL_URL=${SUPABASE_EXT_URL}

############
# Auth (GoTrue)
############

GOTRUE_SITE_URL=${SITE_URL}
GOTRUE_URI_ALLOW_LIST=${ALLOW_LIST}
GOTRUE_DISABLE_SIGNUP=false
GOTRUE_JWT_EXP=3600
GOTRUE_JWT_DEFAULT_GROUP_NAME=authenticated
GOTRUE_MAILER_AUTOCONFIRM=true
GOTRUE_SMS_AUTOCONFIRM=true

############
# Studio
############

STUDIO_DEFAULT_ORGANIZATION=Roka
STUDIO_DEFAULT_PROJECT=Roka
STUDIO_PORT=8000

############
# Frontend
############

NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_EXT_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}

############
# Backend
############

BACKEND_PORT=8100
DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/postgres
ENVEOF

echo ""
echo "Done. Your infra/.env is ready."
echo ""
if [ -n "${ROKA_DOMAIN:-}" ]; then
  echo "Next steps:"
  echo "  docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build"
  echo "  Open ${SITE_URL}"
else
  echo "Next steps:"
  echo "  docker compose up -d"
  echo "  Open http://localhost:3000"
fi
echo "  The setup wizard will guide you through creating an account and configuring your LLM."
echo ""
