#!/usr/bin/env bash
set -euo pipefail

# Roka -- Zero-config bootstrap
# Generates secrets and writes infra/.env.
# Set ROKA_DOMAIN to configure for production.
# Usage:  cd infra && ./setup.sh && docker compose up -d

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"
SEAWEED_S3_JSON="${SCRIPT_DIR}/seaweedfs-s3.json"

# Upgrade path: .env exists but seaweedfs-s3.json missing (e.g. after adding object storage)
if [ -f "$ENV_FILE" ] && [ ! -f "$SEAWEED_S3_JSON" ]; then
  echo "Adding object storage config (seaweedfs-s3.json)..."
  S3_ACCESS_KEY=$(grep -E "^S3_ACCESS_KEY=" "$ENV_FILE" 2>/dev/null | cut -d= -f2- || true)
  S3_SECRET_KEY=$(grep -E "^S3_SECRET_KEY=" "$ENV_FILE" 2>/dev/null | cut -d= -f2- || true)
  if [ -z "$S3_ACCESS_KEY" ] || [ -z "$S3_SECRET_KEY" ]; then
    S3_ACCESS_KEY=$(openssl rand -hex 16)
    S3_SECRET_KEY=$(openssl rand -hex 32)
    cat >> "$ENV_FILE" <<ENVAPPEND

############
# Object Storage (SeaweedFS S3) - auto-added
############

S3_ENDPOINT=http://storage:8333
S3_PUBLIC_ENDPOINT=http://localhost:8333
S3_ACCESS_KEY=${S3_ACCESS_KEY}
S3_SECRET_KEY=${S3_SECRET_KEY}
S3_BUCKET=roka
S3_PORT=8333
ENVAPPEND
  fi
  cat > "$SEAWEED_S3_JSON" <<JSONEOF
{
  "identities": [
    {
      "name": "roka",
      "credentials": [
        { "accessKey": "${S3_ACCESS_KEY}", "secretKey": "${S3_SECRET_KEY}" }
      ],
      "actions": ["Admin", "Read", "Write", "List", "Tagging"]
    }
  ]
}
JSONEOF
  echo "Created ${SEAWEED_S3_JSON}"
  exit 0
fi

if [ -f "$ENV_FILE" ]; then
  echo "infra/.env already exists. Remove it first to regenerate."
  exit 1
fi

echo "Generating secrets..."

POSTGRES_PASSWORD=$(openssl rand -hex 32)
NEXTAUTH_SECRET=$(openssl rand -hex 32)
S3_ACCESS_KEY=$(openssl rand -hex 16)
S3_SECRET_KEY=$(openssl rand -hex 32)

# Determine public URL based on ROKA_DOMAIN env var
if [ -n "${ROKA_DOMAIN:-}" ]; then
  if echo "$ROKA_DOMAIN" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$'; then
    PUBLIC_URL="http://${ROKA_DOMAIN}"
  else
    PUBLIC_URL="https://${ROKA_DOMAIN}"
  fi
  NEXTAUTH_URL="$PUBLIC_URL"
else
  NEXTAUTH_URL="http://localhost:3000"
fi

echo "Writing ${ENV_FILE} ..."

cat > "$ENV_FILE" <<ENVEOF
############
# Secrets (auto-generated by setup.sh)
############

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

############
# Database
############

POSTGRES_USER=postgres
POSTGRES_DB=postgres

############
# Auth (NextAuth.js)
############

NEXTAUTH_URL=${NEXTAUTH_URL}

############
# Backend
############

BACKEND_PORT=8100
DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/postgres

############
# Object Storage (SeaweedFS S3)
############

S3_ENDPOINT=http://storage:8333
S3_PUBLIC_ENDPOINT=http://localhost:8333
S3_ACCESS_KEY=${S3_ACCESS_KEY}
S3_SECRET_KEY=${S3_SECRET_KEY}
S3_BUCKET=roka
S3_PORT=8333
ENVEOF

# Generate SeaweedFS S3 auth config (required for storage service)
echo "Writing ${SEAWEED_S3_JSON} ..."
cat > "$SEAWEED_S3_JSON" <<JSONEOF
{
  "identities": [
    {
      "name": "roka",
      "credentials": [
        { "accessKey": "${S3_ACCESS_KEY}", "secretKey": "${S3_SECRET_KEY}" }
      ],
      "actions": ["Admin", "Read", "Write", "List", "Tagging"]
    }
  ]
}
JSONEOF

echo ""
echo "Done. Your infra/.env is ready."
echo ""
if [ -n "${ROKA_DOMAIN:-}" ]; then
  echo "Next steps:"
  echo "  docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build"
  echo "  Open ${NEXTAUTH_URL}"
else
  echo "Next steps:"
  echo "  docker compose up -d"
  echo "  Open http://localhost:3000"
fi
echo "  The setup wizard will guide you through creating an account and configuring your LLM."
echo ""
