#!/usr/bin/env bash
set -euo pipefail

# Roka -- Zero-config bootstrap
# Generates secrets and writes infra/.env.
# Set ROKA_DOMAIN to configure for production.
# Usage:  cd infra && ./setup.sh && docker compose up -d

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"

if [ -f "$ENV_FILE" ]; then
  echo "infra/.env already exists. Remove it first to regenerate."
  exit 1
fi

echo "Generating secrets..."

POSTGRES_PASSWORD=$(openssl rand -hex 32)
NEXTAUTH_SECRET=$(openssl rand -hex 32)

# Determine public URL based on ROKA_DOMAIN env var
if [ -n "${ROKA_DOMAIN:-}" ]; then
  if echo "$ROKA_DOMAIN" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$'; then
    PUBLIC_URL="http://${ROKA_DOMAIN}"
  else
    PUBLIC_URL="https://${ROKA_DOMAIN}"
  fi
  NEXTAUTH_URL="$PUBLIC_URL"
else
  NEXTAUTH_URL="http://localhost:3000"
fi

echo "Writing ${ENV_FILE} ..."

cat > "$ENV_FILE" <<ENVEOF
############
# Secrets (auto-generated by setup.sh)
############

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

############
# Database
############

POSTGRES_USER=postgres
POSTGRES_DB=postgres

############
# Auth (NextAuth.js)
############

NEXTAUTH_URL=${NEXTAUTH_URL}

############
# Backend
############

BACKEND_PORT=8100
DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/postgres
ENVEOF

echo ""
echo "Done. Your infra/.env is ready."
echo ""
if [ -n "${ROKA_DOMAIN:-}" ]; then
  echo "Next steps:"
  echo "  docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build"
  echo "  Open ${NEXTAUTH_URL}"
else
  echo "Next steps:"
  echo "  docker compose up -d"
  echo "  Open http://localhost:3000"
fi
echo "  The setup wizard will guide you through creating an account and configuring your LLM."
echo ""
